### PR TITLE
Fixed void Map spawn with proxys

### PR DESCRIPTION
**Pull request by suerion**
changed PlayerLoginEvent to PlayerJoinEvent - Fixed the problem, guys spawn in not loaded chunks or in void maps with proxy

### CODE REVIEW

**Comment by suerion** [comment]
#8 should fixed with this

**Comment by dktapps** [comment]
This is a bad fix which wastes a lot of bandwidth sending spawn chunks before teleporting the player. Whatever's wrong here is for Waterdog to fix, not this plugin.

**Comment by suerion** [comment]
Alemiz said, he would not fix it, because it is a plugin problem, i don't know what we should do, i need this plugin for my hub, but the plugin would not fix it and the Waterdog dev would not fix the other problem.

**Comment by dktapps** [comment]
It's obviously not a plugin problem, since the plugin has worked without any change for 2 years until the most recent client update.

**Comment by xxFLORII** [comment]
suerion fix it yourself and make an fork of this plugin or use an another plugin.

**Comment by AGTHARN** [comment]
> changed PlayerLoginEvent to PlayerJoinEvent - Fixed the problem, guys spawn in not loaded chunks or in void maps with proxy

Thanks

**Pull request closed without merging**
